### ISSUE TITLE
MathJax failed to load!

### ISSUE THREAD

**Issue by bogdantoday** [bogdantoday/topams_eec_bsuir#1]
![untitled](https://cloud.githubusercontent.com/assets/8407846/7104727/c36e2ae8-e0fd-11e4-9807-e43a5b25815c.png)

***Firefox 37.0.1***
imageFonts.js loading error here:
```
TypeError: c.FONTDATA.FONTS.MathJax_Main[8212][5] is undefined imageFonts.js:253:10
```
:sob:

**Comment by gldstn** [comment]
Is this problem fixed by your commit?

**Comment by bogdantoday** [comment]
@gldstn no, I just beautified the code :-)
